
export const SET_AUTH_LOGIN = "SET_AUTH_LOGIN"
export const RESET_AUTH ="RESET_AUTH"
export const USER_SIGNUP = "USER_SIGNUP"
export const SET_LOGIN_DESC = "SET_LOGIN_DESC"
export const GET_USERS = "GET_USERS"
export const USER_DELETE = "USER_DELETE"
export const FILE_UPLOAD = "FILE_UPLOAD"
export const GET_POSTS = "GET_POSTS"
export const GETUSER_INFO = "GETUSER_INFO"
export const USERINFO_UPDATE = "USERINFO_UPDATE"
export const PP_UPLOAD = "PP_UPLOAD"
export const POST_LIKE = "POST_LIKE"